name: zhqiyi/DIYMenu
author:
  name: yizhq
  email: yizhqi@gmail.com
  url: null
copyright: 2015 yizhq
description: 'A lightweight, nicely animated modal menu intended to drop below a titlebar of some sort'
